[2024-04-07T04:27:04.563+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: batch_etl.ingest.individual_ingest_movies_rating.end manual__2024-04-07T04:24:26.229890+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
